CREATE TABLE IF NOT EXISTS `student_pre_registration_error_records` (
  `student_pre_registration_id` int(11) NOT NULL AUTO_INCREMENT,
  `student_pre_registration_date` date NOT NULL,
  `student_pre_registration_first_name` varchar(222) NOT NULL,
  `student_pre_registration_last_name` varchar(222) NOT NULL,
  `student_pre_registration_dob` date NOT NULL,
  `student_pre_registration_email` varchar(222) NOT NULL,
  `student_pre_registration_address` text NOT NULL,
  `student_pre_registration_father_first_name` varchar(222) NOT NULL,
  `student_pre_registration_father_last_name` varchar(222) NOT NULL,
  `student_pre_registration_father_occupation` varchar(222) NOT NULL,
  `student_pre_registration_father_office_phone` varchar(15) NOT NULL,
  `student_pre_registration_father_resi_phone` varchar(15) NOT NULL,
  `student_pre_registration_father_mobile` varchar(15) NOT NULL,
  `student_pre_registration_mother_first_name` varchar(222) NOT NULL,
  `student_pre_registration_mother_last_name` varchar(222) NOT NULL,
  `student_pre_registration_mother_occupation` varchar(222) NOT NULL,
  `student_pre_registration_mother_office_phone` varchar(15) NOT NULL,
  `student_pre_registration_mother_resi_phone` varchar(15) NOT NULL,
  `student_pre_registration_mother_mobile` varchar(15) NOT NULL,
  `student_pre_registration_how_to_know` text NOT NULL,
  `student_pre_registration_suggestion` text NOT NULL,
  `student_pre_registration_remarks` text NOT NULL,
  `student_pre_registration_attendent` varchar(222) NOT NULL,
  `student_pre_registration_next_step` text NOT NULL,
  `student_pre_registration_ondate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `student_pre_registration_location` varchar(222) NOT NULL,
  `student_pre_registration_previous_school` varchar(222) NOT NULL,
  `student_pre_registration_session_id` varchar(20) NOT NULL,
  `student_pre_registration_errorList` text NOT NULL,
  PRIMARY KEY (`student_pre_registration_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;